In [101]:
import numpy as np
import pandas as pd

In [102]:
df = pd.DataFrame({
    "C1": [233453, 4562, 2233, 6756],
    "C2": [3456, 5675, 34534, 67467],
    "C3": [1212, 2323, 3434, 4545]
})
df.index = ["a", "b", "c", "d"]
df

       C1     C2    C3
a  233453   3456  1212
b    4562   5675  2323
c    2233  34534  3434
d    6756  67467  4545

A DataFrame column is a series

In [103]:
df.columns

Index(['C1', 'C2', 'C3'], dtype='str')

In [104]:
df.index

Index(['a', 'b', 'c', 'd'], dtype='str')

In [105]:
df.info()

<class 'pandas.DataFrame'>
Index: 4 entries, a to d
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C1      4 non-null      int64
 1   C2      4 non-null      int64
 2   C3      4 non-null      int64
dtypes: int64(3)
memory usage: 132.0 bytes

In [106]:
df.size

12

In [107]:
df.shape

(4, 3)

In [108]:
df.describe()

                  C1            C2           C3
count       4.000000      4.000000     4.000000
mean    61751.000000  27783.000000  2878.500000
std    114482.896647  30005.346468  1434.294833
min      2233.000000   3456.000000  1212.000000
25%      3979.750000   5120.250000  2045.250000
50%      5659.000000  20104.500000  2878.500000
75%     63430.250000  42767.250000  3711.750000
max    233453.000000  67467.000000  4545.000000

In [109]:
df.dtypes

C1    int64
C2    int64
C3    int64
dtype: object

## Indexing, Selection and Slicing

In [110]:
df.loc["a"] # horizontal

C1    233453
C2      3456
C3      1212
Name: a, dtype: int64

In [111]:
df.iloc[0] # horizontal

C1    233453
C2      3456
C3      1212
Name: a, dtype: int64

In [112]:
# Calculate the mean of a column
df.describe().loc["mean"]["C1"]

np.float64(61751.0)

In [113]:
df["C1"] # vertical

a    233453
b      4562
c      2233
d      6756
Name: C1, dtype: int64

In [114]:
df.loc["a": "c"] # UPPER LIMIT INCLUDED

       C1     C2    C3
a  233453   3456  1212
b    4562   5675  2323
c    2233  34534  3434

In [115]:
df.iloc[0: 3] # UPPER LIMIT EXCLUDED

       C1     C2    C3
a  233453   3456  1212
b    4562   5675  2323
c    2233  34534  3434

## Conditional selection (boolean arrays)

In [116]:
df>5000

      C1     C2     C3
a   True  False  False
b  False   True  False
c  False   True  False
d   True   True  False

In [117]:
df.loc[df["C1"]>5000, "C1"]

a    233453
d      6756
Name: C1, dtype: int64

## Dropping stuff

In [118]:
df.drop(["a", "b"])

     C1     C2    C3
c  2233  34534  3434
d  6756  67467  4545

In [119]:
df.drop(columns = ["C1", "C2"])

     C3
a  1212
b  2323
c  3434
d  4545

## Operations

In [120]:
df[["C1", "C2"]] * 10000000

              C1            C2
a  2334530000000   34560000000
b    45620000000   56750000000
c    22330000000  345340000000
d    67560000000  674670000000

In [121]:
crisis = pd.Series([-5555555, -555555555555555555555555], index=["C1", "C2"])
crisis

C1                     -5555555
C2    -555555555555555555555555
dtype: object

In [122]:
df[["C1", "C2"]]

       C1     C2
a  233453   3456
b    4562   5675
c    2233  34534
d    6756  67467

In [123]:
df[["C1", "C2"]] + crisis

         C1                         C2
a  -5322102  -555555555555555555552099
b  -5550993  -555555555555555555549880
c  -5553322  -555555555555555555521021
d  -5548799  -555555555555555555488088

## Modifying DataFrames

In [124]:
c4 = pd.Series([234, 234, 324, 5765675], index=["a", "b", "c", "d"], name="C4")

In [125]:
df["Hello"] = c4
df

       C1     C2    C3    Hello
a  233453   3456  1212      234
b    4562   5675  2323      234
c    2233  34534  3434      324
d    6756  67467  4545  5765675

In [127]:
df["Hello"] = "Everybody"
df

       C1     C2    C3      Hello
a  233453   3456  1212  Everybody
b    4562   5675  2323  Everybody
c    2233  34534  3434  Everybody
d    6756  67467  4545  Everybody

In [130]:
df.rename(columns={"C1": "me"}, index={"a": "you"})

         me     C2    C3      Hello
you  233453   3456  1212  Everybody
b      4562   5675  2323  Everybody
c      2233  34534  3434  Everybody
d      6756  67467  4545  Everybody

### Combining columns

In [131]:
df["C1/C2"] = df["C1"] / df["C2"]
df

       C1     C2    C3      Hello      C1/C2
a  233453   3456  1212  Everybody  67.550058
b    4562   5675  2323  Everybody   0.803877
c    2233  34534  3434  Everybody   0.064661
d    6756  67467  4545  Everybody   0.100138